---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/exposure_by_time/exposure_by_time.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/260401/articles/362072/master/file/figures/exposure_by_time/exposure_by_time.png"
    folder_url: "/users/260401/articles/362072/master/folder/figures/exposure_by_time"
